steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud functions deploy mise \
          --region=us-west1 \
          --runtime=python313 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point=mise \
          --source=.

timeout: 540s

options:
  logging: CLOUD_LOGGING_ONLY